language: python 
python:
  - "2.7"
  - "3.5"
  - "3.6"  # current default Python on Travis CI

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_install:
  - pip install codecov
  - pip install coverage
script: 
  - pip install -e .[tests] --progress-bar off
  - pip install codacy-coverage
  # - pytest tests --cov=pyensemble --cov-report xml:coverage.xml
  - python -m pytest --cov=./ --cov-report xml:coverage.xml
  - if ! [[ -z $CODACY_PROJECT_TOKEN ]]; then
      python-codacy-coverage -r coverage.xml;
    fi
  - pip install python-coveralls && coveralls
  - pip install pytest-cover
after_success:
  - codecov --token="$CODECOV_TOKEN"
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  global:
    - CODACY_PROJECT_TOKEN=2f4bbe5b26b54d3faf45de40c3da9fdd
    - CODECOV_TOKEN = "0e1af558-e8ae-4767-9612-d88ddab8a375"