language: python
cache: pip 
git:
  depth: 3
  quiet: true
  submodules: false
python:
  - "3.6"  # current default Python on Travis CI

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - git clone https://github.com/eustomaqua/PyEnsemble.git
  - pip install -e ./PyEnsemble
# command to run tests
before_script:
  - pip install pyyaml
  - pip install coveralls
  # - pip install coverage==3.7.1
  - pip install codecov
  - pip install pytest pytest-cov==2.5.1
  # - pip install codacy-coverage
script:
  # - pip install -e .[tests] --progress-bar off
  ## - python -m pytest --cov-report xml:coverage.xml
  - coverage run --source=./ -m pytest --ignore=./PyEnsemble
  - coveralls
  - coverage report -m --omit=./PyEnsemble
  # - coverage xml
  # - if ! [[ -z $CODACY_PROJECT_TOKEN ]]; then
  #     python-codacy-coverage -r coverage.xml;
  #   fi
  # - pip install python-coveralls==2.4.3 # && coveralls
  # - pip install pytest-cover
after_success:
  # - coveralls
  - codecov --token="$CODECOV_TOKEN"
  - bash <(curl -s https://codecov.io/bash)
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

env:
  global:
    - CODACY_PROJECT_TOKEN=2f4bbe5b26b54d3faf45de40c3da9fdd
    - CODECOV_TOKEN = "0e1af558-e8ae-4767-9612-d88ddab8a375"